#!/bin/bash

plugin_name="${DOCKER_REPO}.plugin"
#create version tag
mkdir -p rootfs &&
  id=$(docker create "${DOCKER_REPO}:${DOCKER_TAG}" true) &&
  docker export "${id}" | tar -x -C rootfs &&
  docker rm -f "${id}" &&
  docker plugin create "${plugin_name}:${DOCKER_TAG}" . &&
  docker plugin push "${plugin_name}:${DOCKER_TAG}"
#create latest tag
rm -rf rootfs &&
  mkdir -p rootfs &&
  id=$(docker create "${DOCKER_REPO}:${DOCKER_TAG}" true) &&
  docker export "${id}" | tar -x -C rootfs &&
  docker rm -f "${id}" &&
  docker plugin create "${plugin_name}" . &&
  docker plugin push "${plugin_name}"
